### ISSUE TITLE
[Feature Request] Hijack DNS Request to Remote Server Via Proxy

### ISSUE THREAD

**Issue by CoelWu** [Shadowsocks-NET/QvPlugin-WinNetFilter#1]
当代理所有程序的时候, dns请求会由svchost.exe发出。如果用户dns为路由器或者国内dns，dns请求就极有可能被污染，导致无法打开网站。NetFilter的驱动已经拥有管理员权限，不像使用代码修改DNS一样还需要请求管理员权限，不知道在NetFilter中劫持DNS流量并转发到特定dns（比如1.1.1.1, 8.8.8.8) 可不可行。

~~我目前有个想法是在udpSend中粗暴判断端口为53的UDP请求，但是修改了请求地址后程序收不到来自dns服务器的响应。~~

**Comment by database64128** [comment]
![image](https://user-images.githubusercontent.com/18757988/119804530-025f0e80-bf13-11eb-801b-945d31a197b9.png)

You can turn on "DNS intercept".

**Comment by database64128** [comment]
I'm assuming your issue has been resolved. Feel free to reopen if you have more questions.
